### ISSUE TITLE
MODELS DATABASE

### ISSUE THREAD

**Issue by Pirolye** [CaosCreations/JumpingJax#147]
List of models:

- [x] Gas pipeline, broken gas pipeline
- [ ] Low-poly industrial heating machine with ventilators (you know the ones that are on top of highrise buildings)
- [x] Futuristic delivery boxes, like for food or something. Already prototyped with correct scale and light locations. (See: DeliveryBox_solid)
- [x] Low-poly high tech toolbox. The ones that open with multiple layers on top of each other.
- [ ] Window that has a flat inside 
- [x] Multiple flying car models
- [ ] floating traffic lights
- [ ] mile markers, highway traffic direction signs
- [ ] various 2D billboards

**Comment by danielrobnik** [comment]
Asset tracking and requests has moved to Notion.
