### ISSUE TITLE
Modular Pipe Kit

### ISSUE THREAD

**Issue by ambid17** [CaosCreations/JumpingJax#151]
3 separate pipes are needed to make it modular:
- straight pipe
- 90 degree bent pipe
- pipe connector that has a valve

Inspiration: Some combination between these two. The first link has the pipes glowing, which would be perfect. The second is a bit more realistic.
https://www.artstation.com/artwork/g3wNL
https://www.artstation.com/artwork/Z4VZN

**Comment by danielrobnik** [comment]
Asset tracking and requests has moved to Notion.
