### ISSUE TITLE
Player falling through ResetFloor when no checkpoint was hit, should reset to spawn position instead.

### ISSUE THREAD

**Issue by Pirolye** [CaosCreations/JumpingJax#180]
Reproduce with ease:

1. Switch to Hop1-Sabien
2. Start game
3. DO NOT HIT ANY CHECKPOINTS.
4. Crouchjump above balcony window.
5. When hitting the road, the player should reset. They don't.

I don't know if there is any implementation for this, hopefully not, because if yes, it's broken af.

**Comment by ambid17** [comment]
this is intended functionality
